### ISSUE TITLE
No outputs generated when only junit-path is provided

### ISSUE THREAD

**Issue by burakuyar** [xportation/junit-coverage-report#16]
I tried to use action with only `junit-path` and no outputs are generated.
Would it be possible to use the action when only one of unit tests or coverage results are wanted?

**Comment by xportation** [comment]
Yes, it should be possible. 
Please, look at your file content and compare it to the test samples:
https://github.com/xportation/junit-coverage-report/tree/develop/src/__tests__/data

You can also define your custom report:
https://github.com/xportation/junit-coverage-report#custom-reports
